version: '2'
services:
    datascience-notebook:
        image: jupyter/base-notebook:latest
        volumes:
            - /tmp/jupyter_test_dir:/home/docker_worker/work
        ports:
            - 8888:8888
        command: "start-notebook.sh --NotebookApp.token=''" 
